scheduler/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

import solver.views

urlpatterns = patterns('',
    url(r'^$', solver.views.home, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^solver/', include('solver.urls', namespace='solver')),
)

solver/urls.py
from django.conf.urls import patterns, url
from solver import views

urlpatterns = patterns('',
  url(r'^index/$', views.index, name='index'),
  url(r'^$', views.availability_initial, name='initial'),
  url(r'^new_availability/', views.new_availability, name='new_availability'),
  url(r'^availability/(?P<availability_id>\d+)/$', views.availability, name='availability'),
  url(r'^run/(?P<pk>\d+)/$', views.SolverRunView.as_view(), name='run'),
  url(r'^start/$', views.start_run, name='start_run'),
  url(r'^schedule/(?P<pk>\d+)/$', views.ScheduleView.as_view(), name='schedule'),
)

solver/models.py
import ast

from django.db import models

def DictSortedStr(a):
  return ('{' + ', '.join(
      [str(k) + ': ' + str(v) for k, v in sorted(a.items())]) + '}')


class Availability(models.Model):
  creation_time = models.DateTimeField(auto_now_add=True)
  deleted = models.BooleanField(default=False)
  locked = models.BooleanField(default=False)
  slot_times = models.TextField()
  constraints = models.TextField()
  csv_data = models.TextField()
  default_length = models.IntegerField(default=30)

class SolverOptions(models.Model):
  arrive_late_bonus = models.IntegerField()
  leave_early_bonus = models.IntegerField()
  day_off_bonus = models.IntegerField()
  no_break_penalty = models.CharField(max_length=100)
  pupil_preference_penalty_list = models.CommaSeparatedIntegerField(
      max_length=100)
  instructor_preference_penalty_list = models.CommaSeparatedIntegerField(
      max_length=100)
  complex_constraints = models.CharField(max_length=1000)

  def __str__(self):
    d = ast.literal_eval(self.no_break_penalty)
    return ('Arrive Late Bonus: ' + str(self.arrive_late_bonus) +
            '\nLeave Early Bonus: ' + str(self.leave_early_bonus) +
            '\nDay Off Bonus: ' + str(self.day_off_bonus) +
            '\nNo Break Penalty: ' + DictSortedStr(d) +
            '\nPupil Preference Penalties: ' + str(self.pupil_preference_penalty_list) +
            '\nInstructor Preference Penalties: ' + str(self.instructor_preference_penalty_list) +
            '\nComplex Constraints: ' + str(self.complex_constraints) +
            '')

class SolverRun(models.Model):
  creation_time = models.DateTimeField(auto_now_add=True)
  solver_version = models.CharField(max_length=10)
  deleted = models.BooleanField(default=False)

  options = models.ForeignKey(SolverOptions)
  availability = models.ForeignKey(Availability)

  score = models.IntegerField(null=True, blank=True)
  scheduler_output = models.TextField()
  solver_output = models.TextField()

  IN_QUEUE = 'q'
  RUNNING = 'r'
  DONE = 'd'
  FAILED = 'f'
  SOLVER_STATE_CHOICES = (
      (IN_QUEUE, 'Solver Problem Queued'),
      (RUNNING, 'Solver Running'),
      (DONE, 'Solver Done'),
      (FAILED, 'Solver Failed'),
  )
  state = models.CharField(max_length=1, choices=SOLVER_STATE_CHOICES)

  NO_SOLUTION = 'n'
  IMPOSSIBLE = 'i'
  SOLUTION = 's'
  OPTIMAL = 'o'
  SOLUTION_CHOICES = (
      (NO_SOLUTION, 'No Solution Found'),
      (IMPOSSIBLE, 'Problem is Impossible'),
      (SOLUTION, 'Solution Found'),
      (OPTIMAL, 'Optimal Solution Found'),
  )
  solution = models.CharField(max_length=1, choices=SOLUTION_CHOICES)

class Schedule(models.Model):
  creation_time = models.DateTimeField(auto_now_add=True)
  deleted = models.BooleanField(default=False)
  score = models.IntegerField(null=True, blank=True)
  schedule = models.TextField()
  created_by = models.ForeignKey(SolverRun)

  def __str__(self):
    return ('Schedule with score ' + str(self.score) +
            ' created on ' + str(self.creation_time))

solver/views.py
import logging
import ast
import csv
import subprocess

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.views import generic
from django.core.urlresolvers import reverse

from solver.models import *
from solver import solver

logger = logging.getLogger(__name__)

class SolverRunView(generic.DetailView):
  model = SolverRun
  template_name = 'solver/solver_run_detail.html'

class ScheduleView(generic.DetailView):
  model = Schedule

def home(request):
  template = loader.get_template('solver/instructions.html')
  context = RequestContext(request, {
      'version_number': solver.version_number
      })
  return HttpResponse(template.render(context))

def index(request):
  all_availability = Availability.objects.all()
  all_solver_options = SolverOptions.objects.all()
  all_solver_run = SolverRun.objects.all()
  all_schedule = Schedule.objects.all()
  template = loader.get_template('solver/index.html')
  context = RequestContext(request, {
      'all_availability': all_availability,
      'all_solver_options': all_solver_options,
      'all_solver_run': all_solver_run,
      'all_schedule': all_schedule,
  })
  return HttpResponse(template.render(context))

def availability_initial(request):
  template = loader.get_template('solver/availability_initial.html')
  context = RequestContext(request, {})
  return HttpResponse(template.render(context))

def new_availability(request):
  availability = Availability()
  availability.csv_data = request.POST['csv_data']
  availability.save()

  return HttpResponseRedirect(reverse('solver:availability',
                                      args=(availability.id,)))

def availability(request, availability_id):
  availability = get_object_or_404(Availability, pk=availability_id)
  parser = csv.reader(availability.csv_data.splitlines(True))
  table_data = []
  for row in parser:
    if not row:
      continue
    table_data.append([x.strip() for x in row])
  template = loader.get_template('solver/availability_detail.html')
  context = RequestContext(request, {
      'table_data': table_data,
      'availability': availability,
  })
  return HttpResponse(template.render(context))

def start_run(request):
  availability = Availability()
  solver_options = SolverOptions()

  availability.csv_data = request.POST['csv_data']
  availability.default_length = request.POST['default_length']
  availability.save()

  solver_options.arrive_late_bonus = request.POST['arrive_late_bonus']
  solver_options.leave_early_bonus = request.POST['leave_early_bonus']
  solver_options.day_off_bonus = request.POST['day_off_bonus']
  solver_options.no_break_penalty = ast.literal_eval('{'+
      request.POST['no_break_penalty']+'}')
  solver_options.pupil_preference_penalty_list = request.POST['pupil_preference_penalty']
  solver_options.instructor_preference_penalty_list = request.POST['instructor_preference_penalty']
  solver_options.complex_constraints = request.POST['complex_constraints']
  solver_options.save()

  solver_run = SolverRun()
  solver_run.solver_version = solver.version_number
  solver_run.options = solver_options
  solver_run.availability = availability
  solver_run.score = None
  solver_run.state = SolverRun.IN_QUEUE
  solver_run.solution = SolverRun.NO_SOLUTION
  solver_run.save()

  return HttpResponseRedirect(reverse('solver:run', args=(solver_run.id,)))

solver/templates/solver/availability_detail.html
<script>
num_complex_row_added = 0;

function addComplexOrConstraint(base_button) {
  var elem = document.createElement('input');
  elem.type = 'text';
  elem.value = base_button.previousSibling.value;
  base_button.parentNode.insertBefore(document.createTextNode(' Or '), base_button);
  base_button.parentNode.insertBefore(elem, base_button);
}

function addComplexConstraint(constraint) {
  var constraint_row = document.createElement('div');
  constraint_row.style.display = 'table-row';
  var constraint_cell1 = document.createElement('div');
  constraint_cell1.style.display = 'table-cell';
  constraint_row.appendChild(constraint_cell1);
  var constraint_cell2 = document.createElement('div');
  constraint_cell2.style.display = 'table-cell';
  if (num_complex_row_added > 0) {
    constraint_cell2.appendChild(document.createTextNode('And '));
  }
  constraint_row.appendChild(constraint_cell2);
  var constraint_cell3 = document.createElement('div');
  constraint_cell3.style.display = 'table-cell';
  constraint_row.appendChild(constraint_cell3);

  var elem = document.createElement('input');
  elem.type = 'text';
  elem.value = constraint;
  constraint_cell3.appendChild(elem);

  var elem = document.createElement('button');
  elem.type = 'button';
  elem.onclick = function() {addComplexOrConstraint(elem);};
  elem.appendChild(document.createTextNode('Or...'));
  constraint_cell3.appendChild(elem);

  var constraint_table = document.getElementById('complex_constraints');
  constraint_table.appendChild(constraint_row);

  num_complex_row_added++;
}

function addLunchBreak() {
  addComplexConstraint('30min M 11:30-13:30');
  addComplexConstraint('30min T 11:30-13:30');
  addComplexConstraint('30min W 11:30-13:30');
  addComplexConstraint('30min R 11:30-13:30');
  addComplexConstraint('30min F 11:30-13:30');
  addComplexConstraint('30min S 11:30-13:30');
  addComplexConstraint('30min U 11:30-13:30');
}

function getComplexConstraint() {
  var constraint_table = document.getElementById('complex_constraints');
  var output = ''
  first_row = true;
  for (var row_index = 0; row_index < constraint_table.childNodes.length;
       ++row_index) {
    row = constraint_table.childNodes[row_index];
    if (row.nodeName != "DIV") {
      continue;
    }
    if (first_row) {
      first_row = false;
      continue;
    }
    if (output != '') {
      output += ',';
    }
    first_cell = true
    cell = row.childNodes[2]
    for (var list_index = 0; list_index < cell.childNodes.length;
         ++list_index) {
      elem = cell.childNodes[list_index]
      if (elem.nodeName == 'INPUT') {
        if (!first_cell) {
          output += ' OR ';
        }
        first_cell = false;
        output += elem.value;
      }
    }
  }
  return output;
}

</script>
<h1>Step 2: Generic Scheduling Preferences (id {{ availability.id }})</h1>
The CSV data from <a href="{% url 'solver:initial' %}">Step 1</a>.  You probably don't want to edit this manually.  A later version of this application will provide a nice view for editing this data again.<br>

{% if availability.deleted %}
You do not have permission to view this page.
{% else %}

<form action="{% url 'solver:start_run' %}" method="post">
{% csrf_token %}
<textarea name="csv_data" rows="5" cols="150" width=100%>
{% for table_row in table_data %}{{ table_row | join:"," }}
{% endfor %}
</textarea><br>
<br>
Generic penalty and bonus terms.<br>
Default Lesson Length: <input type="text" name="default_length" value="30" size=3 />minutes<br>
Arrive Late Bonus: <input type="text" name="arrive_late_bonus" value="310" size=3 /><br>
Leave Early Bonus: <input type="text" name="leave_early_bonus" value="320" size=3 /><br>
Day Off Bonus: <input type="text" name="day_off_bonus" value="500" size=3 /><br>
No Break Penalty: <input type="text" name="no_break_penalty" value="0: 660, 60: 0, 240: 0, 300: 200, 330: 400, 360: 800, 420:1600, 480:3200, 540: 6400, 600: 12800, 660: 25600" size=150 /><br>
Pupil Preference Penalty (values correspond to 2,3,4,5,etc): <input type="text" name="pupil_preference_penalty" value="100,201,403,807" size=20 /><br>
Instructor Preference Penalty (values correspond to 2,3,4,5,etc): <input type="text" name="instructor_preference_penalty" value="305,620,1290,2600" size=20 /><br>
<div id="complex_constraints" style='display: table;'>
<div style='display: table-row;'>
<div style='display: table-cell;'>Complex Constraints: </div>
<div style='display: table-cell;'></div>
<div style='display: table-cell;'>
<button onclick="addComplexConstraint('30min M 11:30-13:30');" type="button" >Add Constraint</button>
<button onclick="addLunchBreak(); this.hidden = true;" type="button" >Add Lunch Break</button>
</div>
</div>
</div>
<input id="complex_constraints_input" type="text" name="complex_constraints" value="" hidden />
<button type="button" onclick="alert('Not Implemented');">Save</button>
<button type="submit" onclick="document.getElementById('complex_constraints_input').value = getComplexConstraint();">Solve</button><br>
<br>
Unimplemented features: Better Error messaging on failure.<br>
Unimplemented features: Support penalty for consecutive day lessons.<br>
Unimplemented features: different penalties on different days.<br>
Unimplemented features: Save button for this page.<br>
Unimplemented features: Edit button for switching betwen csv and table view of constraints.<br>
Unimplemented features: logged in sessions.<br>
</form>
{% endif %}

solver/templates/solver/index.html
<h1>All pages in the database.</h1>
<p>If you want an example of how to use this application, go to an "availability" page.</p>
{% for availability in all_availability %}
  <a href="{% url 'solver:availability' availability.id %}">{% url 'solver:availability' availability.id %}</a><br>
{% endfor %}
{% for solver_run in all_solver_run %}
  <a href="{% url 'solver:run' solver_run.id %}">{% url 'solver:run' solver_run.id %}</a><br>
{% endfor %}
{% for schedule in all_schedule %}
  <a href="{% url 'solver:schedule' schedule.id %}">{% url 'solver:schedule' schedule.id %}</a><br>
{% endfor %}

solver/templates/solver/instructions.html
<html>
<body>
<h1>Free Online Session Scheduler ({{version_number}})</h1>
<p>Everything you enter on this site becomes publicly accessible.  I reserve the right to keep your data for as long or as short as I feel like it.  If you have confidential information (possibly your pupil's names, if they are unique) please don't upload them here (I don't want to be responsible for someone knowing who will be where at what time).  Please be aware that routine web logging captures your IP address which gives a general geographical indication of where you are accessing this site from.  Don't upload anything that when coupled with this information would compromise someone's safety.  If you are worried, please rename your pupils A, B, C, etc.</p>
<p>This web application solves what is known as the timetabling problem.  In its simplest form, this application will determine the best times to schedule all of your pupils given their preferences and constraints and your preferences and constraints.</p>
<p>Follow <b><a href="solver/">this</a></b> link to go to the application.  I know this website is quite complicated to use, if you have suggestions for how to improve it, please send me an email at manfred.georg@gmail.com .</p>
<p>This project is distributed under the <a href="http://www.gnu.org/licenses/gpl.html">GPL3</a>: <a href="https://github.com/mgeorg/scheduler">source code</a> is available for free on <a href="http://github.com/">github</a>.  Meaning, you can create a copy of this website if you feel like it (and you can be reasonably sure I won't start charging money or that this application will suddenly go away).</p>
<h2>General Instructions</h2>
<ol>
<li>This program is very unforgiving about formatting.  If you encounter an error, check that you haven't added or removed spaces, added or removed commas, changed the capitalization of something, used non-single letter abbreviations for days of the week, changed the order of start times so they aren't chronological or any number of other minor changes.  Let me know, if something is giving you trouble.</li>
<li>Follow the instructions carefully.  If the instructions say you should use a 1 character code for each day of the week and "U" stands for Sunday, then use "U".  Don't use "Sun" and expect the program to understand, it won't.</li>
</ol>
</body>
</html>

solver/templates/solver/schedule_detail.html
<h1>Schedule</h1>
{% if object.deleted %}
You do not have permission to view this page.
{% else %}
<p>Created at: {{object.creation_time}} UTC</p>
<pre>{{ object.schedule }}</pre>
<p>score: {{ object.score }}</p>
{% endif %}

solver/templates/solver/solver_run_detail.html
<h1>Solver Run Detail</h1>
{% if object.deleted %}
You do not have permission to view this page.
{% else %}
<p>Solver Version {{object.solver_version}}</p>
<p>Started at: {{object.creation_time}} UTC</p>
<p>Current State: {{ object.get_state_display }}</p>
<p>Score: {{ object.score }}</p>
<p>Solution: {{ object.get_solution_display }}</p>
{% if object.schedule_set.all %}
<button onclick='document.getElementById("hider").hidden=false; this.hidden=true;'>Show run info</button>
<div id="hider" hidden>
{% else %}
<div id="hider">
{% endif %}
<p>Options: {{ object.options | linebreaks }}</p>
<p>Scheduler Output: {{ object.scheduler_output | linebreaks }}</p>
<p>Optimizer Output: {{ object.solver_output | linebreaks }}</p>
</div>

{% for schedule in object.schedule_set.all %}
<h2>Schedule</h2>
{% if schedule.deleted %}
You do not have permission to view this schedule.
{% else %}
<p>Created at: {{schedule.creation_time}} UTC</p>
<p>score: {{ schedule.score }}</p>
<pre>{{ schedule.schedule }}</pre>
{% endif %}
{% endfor %}

{% if object.state == solverrun.RUNNING or object.state == solverrun.IN_QUEUE %}
<script>
setTimeout(function(){
  window.location.reload(1);
}, 1000);
</script>
{% for x in "0123456789" %}
<br>
{% endfor %}
{% endif %}

{% endif %}